import 'package:expense_tracker/core/utils/shared_prefs_helper.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class AppLanguage {
  final String code;
  final String name;
  final String flag;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.flag,
  });
}

class LanguageProvider extends ChangeNotifier {
  final List<AppLanguage> supportedLanguages = const [
    AppLanguage(code: 'en', name: 'English', flag: '🇺🇸'),
    AppLanguage(code: 'bn', name: 'Bangla', flag: '🇧🇩'),
    AppLanguage(code: 'hi', name: 'Hindi', flag: '🇮🇳'),
    AppLanguage(code: 'ur', name: 'Urdu', flag: '🇵🇰'),
  ];

  String _currentLanguageCode = 'en';

  String get currentLanguageCode => _currentLanguageCode;

  AppLanguage get currentLanguage {
    return supportedLanguages.firstWhere(
      (l) => l.code == _currentLanguageCode,
      orElse: () => supportedLanguages.first,
    );
  }

  LanguageProvider() {
    _loadLanguage();
  }

  void _loadLanguage() {
    final savedCode = SharedPrefsHelper.getString('app_language_code');
    if (savedCode != null) {
      _currentLanguageCode = savedCode;
    }
  }

  Future<void> changeLanguage(String code) async {
    if (_currentLanguageCode != code) {
      _currentLanguageCode = code;
      await SharedPrefsHelper.setString('app_language_code', code);
      notifyListeners();
    }
  }

  String translate(String key) {
    return _localizedValues[_currentLanguageCode]?[key] ?? 
           _localizedValues['en']?[key] ?? 
           key;
  }
}

extension TranslationExtension on BuildContext {
  String translate(String key) {
    return Provider.of<LanguageProvider>(this).translate(key);
  }
}

const Map<String, Map<String, String>> _localizedValues = {
  'en': {
    'home': 'Home',
    'ledger': 'Ledger',
    'analytics': 'Analytics',
    'settings': 'Settings',
    'quick_actions': 'Quick Actions',
    'edit_menu': 'Edit Menu',
    'income': 'Income',
    'expense': 'Expense',
    'to_receive': 'To Receive',
    'to_give': 'To Give',
    'recent_activity': 'Recent Activity',
    'view_all': 'View All',
    'distribution': 'Distribution',
    'budget_status': 'Budget Status',
    'preferences': 'Preferences',
    'currency': 'Currency',
    'theme': 'Theme',
    'change_language': 'Change Language',
    'notifications': 'Notifications',
    'management': 'Management',
    'manage_categories': 'Manage Categories',
    'view_reports': 'View Reports',
    'select_language': 'Select Language',
    'no_notifications': 'No Notifications Yet !',
    'all_caught_up': "You're all caught up! We'll notify you when somethings new comes up.",
    'add_income': 'Add Income',
    'add_expense': 'Add Expense',
    'category': 'Category',
    'date': 'Date',
    'income_month': 'Income Month',
    'save_income': 'Save Income',
    'save_expense': 'Save Expense',
    'cancel': 'Cancel',
    'add': 'Add',
    'add_new_category': 'Add New Category',
    'search_category': 'Search Category...',
    'profile': 'Profile',
    'logout': 'Logout',
    'add_note': 'Add Note',
    'payment_out': 'Payment Out',
    'payment_in': 'Payment In',
    'pending': 'pending',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'days_ago': 'days ago',
    'search_hint': 'Search note or category...',
    'total_balance': 'Total Balance',
    'total_spending': 'Total Spending',
    'this_month': 'This Month',
    'previous_month': 'Previous Month',
    'top_spending_categories': 'Top Spending Categories',
    'no_transactions': 'No Transactions',
    // New keys
    'electronics': 'Electronics',
    'entertainment': 'Entertainment',
    'medicine': 'Medicine',
    'salary': 'Salary',
    'rent': 'Rent',
    'housing': 'Housing',
    'food': 'Food',
    'transport': 'Transport',
    'utilities': 'Utilities',
    'sort_transactions': 'Sort Transactions',
    'sort_latest': 'Latest',
    'sort_amount_high_low': 'Amount: High to Low',
    'sort_amount_low_high': 'Amount: Low to High',
    'all': 'All',
    'alerts': 'Alerts',
    'updates': 'Updates',
    'mark_read': 'Mark read',
    'close': 'Close',
    'account': 'Account',
    'personal_info': 'Personal Information',
    'password_change': 'Password Change',
    'notebook': 'Notebook',
    'support': 'Support',
    'help_center': 'Help Center',
    'privacy_policy': 'Privacy Policy',
    'no_categories_yet': 'No categories created yet.',
    'select_report_type': 'Select Report Type',
    'expense_insights': 'Expense Insights',
    'income_insights': 'Income Insights',
    'highest_expenditure_areas': 'Highest expenditure areas',
    'current_month_distribution': 'Current Month Distribution',
    'total': 'Total',
    'rent_maintenance': 'Rent & Maintenance',
    'groceries_dining': 'Groceries & Dining',
    'fuel_transit': 'Fuel & Transit',
    'for': 'For',
  },
  'bn': {
    'home': 'হোম',
    'ledger': 'লেজার',
    'analytics': 'বিশ্লেষণ',
    'settings': 'সেটিংস',
    'quick_actions': 'কুইক অ্যাকশন',
    'edit_menu': 'মেনু সম্পাদনা',
    'income': 'আয়',
    'expense': 'ব্যয়',
    'to_receive': 'পাওনা',
    'to_give': 'দেনা',
    'recent_activity': 'সাম্প্রতিক লেনদেন',
    'view_all': 'সব দেখুন',
    'distribution': 'বন্টন',
    'budget_status': 'বাজেটের অবস্থা',
    'preferences': 'পছন্দসমূহ',
    'currency': 'মুদ্রা',
    'theme': 'থিম',
    'change_language': 'ভাষা পরিবর্তন করুন',
    'notifications': 'নোটিফিকেশন',
    'management': 'ব্যবস্থাপনা',
    'manage_categories': 'ক্যাটাগরি পরিচালনা',
    'view_reports': 'রিপোর্ট দেখুন',
    'select_language': 'ভাষা নির্বাচন করুন',
    'no_notifications': 'কোন নোটিফিকেশন নেই!',
    'all_caught_up': 'আপনি সম্পূর্ণ আপডেট আছেন! নতুন কিছু আসলে জানানো হবে।',
    'add_income': 'আয় যোগ করুন',
    'add_expense': 'ব্যয় যোগ করুন',
    'category': 'ক্যাটাগরি',
    'date': 'তারিখ',
    'income_month': 'আয়ের মাস',
    'save_income': 'আয় সংরক্ষণ করুন',
    'save_expense': 'ব্যয় সংরক্ষণ করুন',
    'cancel': 'বাতিল',
    'add': 'যোগ করুন',
    'add_new_category': 'নতুন ক্যাটাগরি যোগ করুন',
    'search_category': 'ক্যাটাগরি খুঁজুন...',
    'profile': 'প্রোফাইল',
    'logout': 'লগআউট',
    'add_note': 'নোট যোগ করুন',
    'payment_out': 'পেমেন্ট আউট',
    'payment_in': 'পেমেন্ট ইন',
    'pending': 'অপেক্ষমান',
    'today': 'আজ',
    'yesterday': 'গতকাল',
    'days_ago': 'দিন আগে',
    'search_hint': 'নোট বা ক্যাটাগরি খুঁজুন...',
    'total_balance': 'মোট ব্যালেন্স',
    'total_spending': 'মোট খরচ',
    'this_month': 'এই মাস',
    'previous_month': 'গত মাস',
    'top_spending_categories': 'শীর্ষ ব্যয় ক্যাটাগরি',
    'no_transactions': 'কোন লেনদেন নেই',
    // New keys
    'electronics': 'ইলেকট্রনিক্স',
    'entertainment': 'বিনোদন',
    'medicine': 'ঔষধ',
    'salary': 'বেতন',
    'rent': 'ভাড়া',
    'housing': 'আবাসন',
    'food': 'খাবার',
    'transport': 'পরিবহন',
    'utilities': 'ইউটিলিটি',
    'sort_transactions': 'লেনদেন সাজান',
    'sort_latest': 'সর্বশেষ',
    'sort_amount_high_low': 'পরিমাণ: বেশি থেকে কম',
    'sort_amount_low_high': 'পরিমাণ: কম থেকে বেশি',
    'all': 'সব',
    'alerts': 'সতর্কতা',
    'updates': 'আপডেট',
    'mark_read': 'পঠিত চিহ্নিত করুন',
    'close': 'বন্ধ করুন',
    'account': 'অ্যাকাউন্ট',
    'personal_info': 'ব্যক্তিগত তথ্য',
    'password_change': 'পাসওয়ার্ড পরিবর্তন',
    'notebook': 'নোটবুক',
    'support': 'সহায়তা',
    'help_center': 'সহায়তা কেন্দ্র',
    'privacy_policy': 'গোপনীয়তা নীতি',
    'no_categories_yet': 'এখনো কোনো ক্যাটাগরি তৈরি করা হয়নি।',
    'select_report_type': 'রিপোর্টের ধরন নির্বাচন করুন',
    'expense_insights': 'ব্যয় বিশ্লেষণ',
    'income_insights': 'আয় বিশ্লেষণ',
    'highest_expenditure_areas': 'সর্বোচ্চ ব্যয়ের খাত',
    'current_month_distribution': 'চলতি মাসের বন্টন',
    'total': 'মোট',
    'rent_maintenance': 'ভাড়া ও রক্ষণাবেক্ষণ',
    'groceries_dining': 'মুদি ও খাবার',
    'fuel_transit': 'জ্বালানি ও পরিবহন',
    'for': 'জন্য',
  },
  'hi': {
    'home': 'होम',
    'ledger': 'खाता बही',
    'analytics': 'विश्लेषण',
    'settings': 'सेटिंग्स',
    'quick_actions': 'त्वरित कार्रवाई',
    'edit_menu': 'मेन्यू संपादित करें',
    'income': 'आय',
    'expense': 'व्यय',
    'to_receive': 'प्राप्त करना है',
    'to_give': 'देना है',
    'recent_activity': 'हाल की गतिविधि',
    'view_all': 'सभी देखें',
    'distribution': 'वितरण',
    'budget_status': 'बजट स्थिति',
    'preferences': 'वरीयताएँ',
    'currency': 'मुद्रा',
    'theme': 'थीम',
    'change_language': 'भाषा बदलें',
    'notifications': 'सूचनाएं',
    'management': 'प्रबंधन',
    'manage_categories': 'श्रेणियों का प्रबंधन',
    'view_reports': 'रिपोर्ट देखें',
    'select_language': 'भाषा चुनें',
    'no_notifications': 'अभी कोई सूचना नहीं!',
    'all_caught_up': 'आप पूरी तरह से अपडेट हैं! कुछ नया आने पर हम सूचित करेंगे।',
    'add_income': 'आय जोड़ें',
    'add_expense': 'व्यय जोड़ें',
    'category': 'श्रेणी',
    'date': 'दिनांक',
    'income_month': 'आय का महीना',
    'save_income': 'आय सहेजें',
    'save_expense': 'व्यय सहेजें',
    'cancel': 'रद्द करें',
    'add': 'जोड़ें',
    'add_new_category': 'नई श्रेणी जोड़ें',
    'search_category': 'श्रेणी खोजें...',
    'profile': 'प्रोफ़ाइल',
    'logout': 'लॉगआउट',
    'add_note': 'नोट जोड़ें',
    'payment_out': 'भुगतान बाहर',
    'payment_in': 'भुगतान अंदर',
    'pending': 'लंबित',
    'today': 'आज',
    'yesterday': 'कल',
    'days_ago': 'दिन पहले',
    'search_hint': 'नोट या श्रेणी खोजें...',
    'total_balance': 'कुल बैलेंस',
    'total_spending': 'कुल खर्च',
    'this_month': 'इस महीने',
    'previous_month': 'पिछला महीना',
    'top_spending_categories': 'शीर्ष खर्च श्रेणियां',
    'no_transactions': 'कोई लेनदेन नहीं',
    // New keys
    'electronics': 'इलेक्ट्रॉनिक्स',
    'entertainment': 'मनोरंजन',
    'medicine': 'दवा',
    'salary': 'वेतन',
    'rent': 'किराया',
    'housing': 'आवास',
    'food': 'भोजन',
    'transport': 'परिवहन',
    'utilities': 'उपयोगिताएँ',
    'sort_transactions': 'लेनदेन क्रमबद्ध करें',
    'sort_latest': 'नवीनतम',
    'sort_amount_high_low': 'राशि: उच्च से निम्न',
    'sort_amount_low_high': 'राशि: निम्न से उच्च',
    'all': 'सभी',
    'alerts': 'अलर्ट',
    'updates': 'अपडेट',
    'mark_read': 'पढ़ा हुआ चिह्नित करें',
    'close': 'बंद करें',
    'account': 'अकाउंट',
    'personal_info': 'व्यक्तिगत जानकारी',
    'password_change': 'पासवर्ड बदलें',
    'notebook': 'नोटबुक',
    'support': 'सहायता',
    'help_center': 'सहायता केंद्र',
    'privacy_policy': 'गोपनीयता नीति',
    'no_categories_yet': 'अभी तक कोई श्रेणी नहीं बनाई गई है।',
    'select_report_type': 'रिपोर्ट का प्रकार चुनें',
    'expense_insights': 'व्यय अंतर्दृष्टि',
    'income_insights': 'आय अंतर्दृष्टि',
    'highest_expenditure_areas': 'उच्चतम व्यय क्षेत्र',
    'current_month_distribution': 'चालू माह का वितरण',
    'total': 'कुल',
    'rent_maintenance': 'किराया और रखरखाव',
    'groceries_dining': 'किराना और भोजन',
    'fuel_transit': 'ईंधन और पारगमन',
    'for': 'के लिए',
  },
  'ur': {
    'home': 'ہوم',
    'ledger': 'لیجر',
    'analytics': 'تجزیہ',
    'settings': 'سیٹنگز',
    'quick_actions': 'فوری اقدامات',
    'edit_menu': 'ترمیم مینو',
    'income': 'آمدنی',
    'expense': 'اخراجات',
    'to_receive': 'وصول کرنا ہے',
    'to_give': 'دینا ہے',
    'recent_activity': 'حالیہ سرگرمی',
    'view_all': 'سب دیکھیں',
    'distribution': 'تقسیم',
    'budget_status': 'بجٹ کی صورتحال',
    'preferences': 'ترجیحات',
    'currency': 'کرنسی',
    'theme': 'تھیم',
    'change_language': 'زبان تبدیل کریں',
    'notifications': 'نوٹیفیکیشنز',
    'management': 'انتظامیہ',
    'manage_categories': 'اقسام کا انتظام',
    'view_reports': 'رپورٹس دیکھیں',
    'select_language': 'زبان منتخب کریں',
    'no_notifications': 'ابھی کوئی نوٹیفکیشن نہیں ہے!',
    'all_caught_up': 'آپ مکمل طور پر اپ ڈیٹ ہیں! کچھ نیا آنے پر ہم مطلع کریں گے۔',
    'add_income': 'آمدنی شامل کریں',
    'add_expense': 'اخراجات شامل کریں',
    'category': 'زمرہ',
    'date': 'تاریخ',
    'income_month': 'آمدنی کا مہینہ',
    'save_income': 'آمدنی محفوظ کریں',
    'save_expense': 'اخراجات محفوظ کریں',
    'cancel': 'منسوخ کریں',
    'add': 'شامل کریں',
    'add_new_category': 'نئی زمرہ شامل کریں',
    'search_category': 'زمرہ تلاش کریں...',
    'profile': 'پروفائل',
    'logout': 'لاگ آؤٹ',
    'add_note': 'نوٹ شامل کریں',
    'payment_out': 'ادائیگی باہر',
    'payment_in': 'ادائیگی اندر',
    'pending': 'زیر التواء',
    'today': 'آج',
    'yesterday': 'کل',
    'days_ago': 'دن پہلے',
    'search_hint': 'نوٹ یا زمرہ تلاش کریں...',
    'total_balance': 'کل بیلنس',
    'total_spending': 'کل اخراجات',
    'this_month': 'اس مہینے',
    'previous_month': 'پچھلے مہینے',
    'top_spending_categories': 'سرفہرست اخراجات کے زمرے',
    'no_transactions': 'کوئی لین دین نہیں',
    // New keys
    'electronics': 'الیکٹرانکس',
    'entertainment': 'تفریح',
    'medicine': 'دوا',
    'salary': 'تنخواہ',
    'rent': 'کرایہ',
    'housing': 'رہائش',
    'food': 'کھانا',
    'transport': 'ٹرانسپورٹ',
    'utilities': 'یوٹیلیٹیز',
    'sort_transactions': 'لین دین کو ترتیب دیں',
    'sort_latest': 'حالیہ',
    'sort_amount_high_low': 'رقم: زیادہ سے کم',
    'sort_amount_low_high': 'رقم: کم سے زیادہ',
    'all': 'تمام',
    'alerts': 'انتباہات',
    'updates': 'اپ ڈیٹس',
    'mark_read': 'پڑھا ہوا نشان زد کریں',
    'close': 'بند کریں',
    'account': 'اکاؤنٹ',
    'personal_info': 'ذاتی معلومات',
    'password_change': 'پاس ورڈ تبدیل کریں',
    'notebook': 'نوٹ بک',
    'support': 'سپورٹ',
    'help_center': 'سپورٹ سینٹر',
    'privacy_policy': 'رازداری کی پالیسی',
    'no_categories_yet': 'ابھی تک کوئی زمرہ نہیں بنایا گیا ہے۔',
    'select_report_type': 'رپورٹ کی قسم منتخب کریں',
    'expense_insights': 'اخراجات کی تفصیلات',
    'income_insights': 'آمدنی کی تفصیلات',
    'highest_expenditure_areas': 'سب سے زیادہ اخراجات کے شعبے',
    'current_month_distribution': 'موجودہ مہینے کی تقسیم',
    'total': 'کل',
    'rent_maintenance': 'کرایہ اور دیکھ بھال',
    'groceries_dining': 'گروسری اور ڈائننگ',
    'fuel_transit': 'ایندھن اور ٹرانزٹ',
    'for': 'کے لیے',
  }
};
