import 'package:lucide_icons_flutter/lucide_icons.dart';
import 'package:flutter/material.dart';

final categoryIcons = <IconData>[
  LucideIcons.tag,
  LucideIcons.utensilsCrossed,
  LucideIcons.coffee,
  LucideIcons.cigarette,
  LucideIcons.droplets,
  LucideIcons.car,
  LucideIcons.hotel,
  LucideIcons.mountain,
  LucideIcons.shoppingBag,
  LucideIcons.beer,
  LucideIcons.shoppingCart,
  LucideIcons.fuel,
  LucideIcons.ticket,
  LucideIcons.moreHorizontal,
  LucideIcons.plane,
  LucideIcons.music,
  LucideIcons.checkCircle,
  LucideIcons.arrowDown,
  LucideIcons.users,
  LucideIcons.compass,
  LucideIcons.image,
  LucideIcons.fileText,
  LucideIcons.arrowLeftRight,
  LucideIcons.camera,
  LucideIcons.image,
  LucideIcons.info,
  LucideIcons.trash,
  LucideIcons.plus,
  LucideIcons.x,
  LucideIcons.gripHorizontal,
  LucideIcons.pin,
  LucideIcons.percent,
  LucideIcons.user,
  LucideIcons.check,
  LucideIcons.calendar,
  LucideIcons.receipt,
  LucideIcons.wallet,
  LucideIcons.chevronDown,
  LucideIcons.alertCircle,
  LucideIcons.minusCircle,
  LucideIcons.arrowLeft,
  LucideIcons.chevronRight,
  LucideIcons.arrowLeft,
  LucideIcons.home,
  LucideIcons.pawPrint,
  LucideIcons.heartPulse,
  LucideIcons.zap,
  LucideIcons.sparkles,
  LucideIcons.cake,
  LucideIcons.gift,
  LucideIcons.wifi,
  LucideIcons.phone,
  LucideIcons.hardHat,
  LucideIcons.paintbrush,
  LucideIcons.trees,
  LucideIcons.umbrella,
];

final iconSearchData = <IconData, String>{
  LucideIcons.tag: 'label tag category other misc general',
  LucideIcons.utensilsCrossed: 'food restaurant dining meal eat dinner lunch',
  LucideIcons.coffee: 'coffee tea breakfast cafe drink beverage morning',
  LucideIcons.cigarette: 'cigarette smoking tobacco cigar',
  LucideIcons.droplets: 'water drink hydration bottle liquid',
  LucideIcons.car: 'transport car vehicle travel drive ride',
  LucideIcons.hotel: 'hotel accommodation stay lodging room',
  LucideIcons.mountain: 'activity outdoor adventure sport hiking trek',
  LucideIcons.shoppingBag: 'shopping bag purchase retail store',
  LucideIcons.beer: 'bar drink alcohol beer wine cocktail party',
  LucideIcons.shoppingCart: 'grocery supermarket food shopping cart',
  LucideIcons.fuel: 'fuel gas station petrol car vehicle',
  LucideIcons.ticket: 'ticket ticket booking event movie show',
  LucideIcons.moreHorizontal: 'more other misc extra additional',
  LucideIcons.plane: 'flight plane travel airport trip vacation',
  LucideIcons.music: 'music song entertainment party concert',
  LucideIcons.checkCircle: 'check done complete confirm yes verified',
  LucideIcons.arrowDown: 'down arrow download receive incoming',
  LucideIcons.users: 'people group team friends family members',
  LucideIcons.compass: 'explore adventure discover compass navigate',
  LucideIcons.image: 'photo image picture gallery photography',
  LucideIcons.fileText: 'document description file report text',
  LucideIcons.arrowLeftRight: 'swap transfer exchange switch change',
  LucideIcons.camera: 'camera photo image picture photography',
  LucideIcons.info: 'info information help details notice',
  LucideIcons.trash: 'delete remove trash discard',
  LucideIcons.plus: 'add new create plus additional',
  LucideIcons.x: 'close cancel exit remove stop',
  LucideIcons.gripHorizontal: 'drag handle move reorder',
  LucideIcons.pin: 'pin save bookmark important',
  LucideIcons.percent: 'percent percentage discount offer sale',
  LucideIcons.user: 'person user people individual',
  LucideIcons.check: 'check done yes confirm verify',
  LucideIcons.calendar: 'calendar date event schedule appointment',
  LucideIcons.receipt: 'receipt bill invoice payment transaction',
  LucideIcons.wallet: 'wallet account balance finance money bank payment',
  LucideIcons.chevronDown: 'keyboard arrow down dropdown expand',
  LucideIcons.alertCircle: 'error warning alert problem issue',
  LucideIcons.minusCircle: 'remove circle delete clear cancel',
  LucideIcons.arrowLeft: 'arrow back left previous return ios',
  LucideIcons.chevronRight: 'chevron right next forward continue',
  LucideIcons.home: 'home house rent lodging accommodation',
  LucideIcons.pawPrint: 'pets animal dog cat pet veterinary',
  LucideIcons.heartPulse: 'health medical medicine hospital doctor pharmacy',
  LucideIcons.zap: 'flash electricity power energy utility bill',
  LucideIcons.sparkles: 'celebration party event occasion festival',
  LucideIcons.cake: 'cake dessert birthday sweet bakery',
  LucideIcons.gift: 'gift present card giftcard occasion',
  LucideIcons.wifi: 'wifi internet network connection data',
  LucideIcons.phone: 'phone mobile call communication mobile',
  LucideIcons.hardHat: 'construction repair maintenance tool fix',
  LucideIcons.paintbrush: 'paint color decoration design art renovate brush',
  LucideIcons.trees: 'forest nature tree park outdoor environment',
  LucideIcons.umbrella: 'beach ocean sea water vacation holiday',
};
