// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpFiPDkvmqo4qle0K8xxwYPD6P6dnAKME',
    appId: '1:1018341294472:web:5aeffc6f1e0643c2883a3d',
    messagingSenderId: '1018341294472',
    projectId: 'expense-tracker-8a3c5',
    authDomain: 'expense-tracker-8a3c5.firebaseapp.com',
    storageBucket: 'expense-tracker-8a3c5.firebasestorage.app',
    measurementId: 'G-7XC1NBTGHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-zmXQLS_hckmZJguhMiLHM6dtYEpX_9Y',
    appId: '1:1018341294472:android:25899d828fafe9ad883a3d',
    messagingSenderId: '1018341294472',
    projectId: 'expense-tracker-8a3c5',
    storageBucket: 'expense-tracker-8a3c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7yLyUnVOlloss0PKYjC8iTE8Gzh1KPj4',
    appId: '1:1018341294472:ios:05fcfd69a210f973883a3d',
    messagingSenderId: '1018341294472',
    projectId: 'expense-tracker-8a3c5',
    storageBucket: 'expense-tracker-8a3c5.firebasestorage.app',
    iosBundleId: 'com.onesttech.budgetmint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7yLyUnVOlloss0PKYjC8iTE8Gzh1KPj4',
    appId: '1:1018341294472:ios:05fcfd69a210f973883a3d',
    messagingSenderId: '1018341294472',
    projectId: 'expense-tracker-8a3c5',
    storageBucket: 'expense-tracker-8a3c5.firebasestorage.app',
    iosBundleId: 'com.onesttech.budgetmint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpFiPDkvmqo4qle0K8xxwYPD6P6dnAKME',
    appId: '1:1018341294472:web:6641523e20a8ef88883a3d',
    messagingSenderId: '1018341294472',
    projectId: 'expense-tracker-8a3c5',
    authDomain: 'expense-tracker-8a3c5.firebaseapp.com',
    storageBucket: 'expense-tracker-8a3c5.firebasestorage.app',
    measurementId: 'G-28NS3XVE93',
  );
}
